development:
  adapter: postgresql
  database: us_state_universities
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432

test:
  adapter: postgresql
  database: us_state_universities_test
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432

production:
  adapter: postgresql
  database: us_state_universities
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432